language: swift

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env: SWIFT=4.1.2

    - os: osx
      osx_image: xcode10.1
      env: SWIFT=4.2.1

    - os: osx
      osx_image: xcode10.3
      env: SWIFT=5.0.3

    - os: osx
      osx_image: xcode11.3
      env: SWIFT=5.1.3

script:
  - /bin/bash Tests/test-script.sh
