os: osx
language: generic

jobs:
  include:
    - osx_image: xcode9.4
      env: SWIFT=4.1.2

    - osx_image: xcode10.1
      env: SWIFT=4.2.1

    - osx_image: xcode10.3
      env: SWIFT=5.0.3

    - osx_image: xcode11.3
      env: SWIFT=5.1.3

script:
  - /bin/bash Utilities/validate-gybbed-files.sh
  - /bin/bash Tests/test-script.sh
