language: swift

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env: SWIFT=4.1.2

    - os: osx
      osx_image: xcode10.1
      env: SWIFT=4.2.1

    - os: osx
      osx_image: xcode10.2
      env: SWIFT=5.0

script:
  - /bin/bash Tests/test-script.sh
